name: code-review

permissions:
  contents: read
  pull-requests: write

on:
  pull-requests:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Get git diff
        run: |
          git fetch origin "${{ github.event.pull_request.head.ref }}"
          git fetch origin "${{ github.event.pull_request.base.ref }}"
          git checkout "${{ github.event.pull_request.head.ref }}"
          git diff "origin/${{ github.event.pull_request.base.ref }}" > "diff.txt"
          {
            echo "pull_request_diff<<EOF";
            cat "diff.txt";
            echo "EOF";
          } >> $GITHUB_OUTPUT
