name: code-review

on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
      - name: Install GoogleGenerativeAI
        run: |
          npm install @google/generative-ai
      - name: Get git diff
        run: |
          git fetch origin "${{ github.event.pull_request.base.ref }}"
          git fetch origin "${{ github.event.pull_request.head.ref }}"
          git diff "origin/${{ github.event.pull_request.base.ref }}" > "diff.txt"
      # - name: Run
      #   uses: actions/github-script@v7
      #   with:
      #     script: |
      #       const { GoogleGenerativeAI } = require("@google/generative-ai");
      #       const genAI = new GoogleGenerativeAI("${{ secrets.GEMINI_API_KEY }}");
      #       const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash"});
      - name: Add PR Review Comment
        uses: nbaztec/add-pr-review-comment@v1.0.7
        with:
          comments: |
            [{"path":"math_.py","line":4,"text":"comment1","side":"RIGHT"},{"path":"math_.py","line":10,"text":"comment2","side":"LEFT"}]
          repo-token: ${{ secrets.GH_TOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: false # This is the default    